name = "PaperJack"
license = "MIT"
licenselink = "https://github.com/jack-hk/PaperJack/blob/main/LICENSE"
description = "A theme made for Jack's Portfolio"
homepage = "https://www.jackhk.com/"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "archive",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.112.4"

[author]
  name = "Jack Hughes-King"
  homepage = "https://www.jackhk.com/"

# If porting an existing theme
[original]
  name = "PaperMod"
  author = "nanxiaobei"
  homepage = "https://github.com/adityatelange/"
  repo = "https://adityatelange.github.io/hugo-PaperMod/"
